### ISSUE TITLE
Add Some Item to AIblacklist please

### ISSUE THREAD

**Issue by CSOLYOO** [ThinkInvis/RoR2-ClassicItems#20]
Headstompers
Snake Eyes
Life Savings
56 Leaf Clover
Golden Gun
Smart Shopper
Photon Jetpack

**Comment by ThinkInvis** [comment]
I didn't know about that tag, thanks! Assuming it's to prevent evolution/arena from granting items that are useless on enemies: Headstompers should still proc if the enemy is launched by knockback or jumps from high ground, and Snake Eyes should give some benefit to enemies if global shrine mode is on (players will risk giving the enemy crit chance when they hit a chance shrine). Fixed by e1658029596fc64eb715f40554c0f9f34698de32.
