### ISSUE TITLE
Ancient spear + mobile turrets doesn't let me place more than 2 turrets

### ISSUE THREAD

**Issue by nickg11** [ThinkInvis/RoR2-ClassicItems#38]
I got the ancient spear by buying from a chest in the bazaar between times using the bigger bazaar mod I also had share suite on so it went directly to my inventory instead of dropping onto the ground. It highlighted the turret ability as purple and said in the description that I could hold and place 2 more turrets. I tried placing a third turret and it destroyed my first one,

**Comment by ThinkInvis** [comment]
Can't reproduce this bug; a console log would be helpful.

**Comment by nickg11** [comment]
I am unable to find the logs for the session I was playing. I also had other mods on so there is a potential issue there. The main one I can think of is skills++, there might be an issue with how the two mods interact with skill replacement overlap.

**Comment by ThinkInvis** [comment]
That's probably it. IIRC, Skills++ recently added an Engi upgrade which does the exact same thing as Ancient Scepter. Scepter's implementation adds to the deployable cap instead of overriding it; if Skills++ does the latter and loads after ClassicItems, it would definitely break compatibility. I'd recommend disabling Ancient Scepter entirely (via config) while Skills++ is loaded, as there are probably other similar incompatibilities.

**Comment by nickg11** [comment]
As of 0.0.10 of Skills++ they have fixed the interaction between the sceptre and the skill upgrades
