### ISSUE TITLE
Disabling Photon Jetpack also disables Kjaro's Band

### ISSUE THREAD

**Issue by ghgrade-a** [ThinkInvis/RoR2-ClassicItems#42]
Disabling Photon Jetpack via the configuration file also disables Kjaro's Band within the Artifact of Command selection menu.

<img width="620" alt="Untitled" src="https://user-images.githubusercontent.com/66977752/84715274-97047280-af35-11ea-8b61-95742360fa53.png">
[LogOutput.log](https://github.com/ThinkInvis/RoR2-ClassicItems/files/4783460/LogOutput.log)

**Comment by ThinkInvis** [comment]
This is an issue with Risk of Rain 2, and it's widespread enough that it's extremely difficult to address with a mod. The root of the problem is that the ItemMask class uses 2 ulongs as the mask, so any ItemIndex past 256 loops back around to 128 (start of the second submask).

Keeping issue open as a reminder -- this may be addressed by the next game update.

**Comment by ThinkInvis** [comment]
Update: heard secondhand that the devs are planning on patching this sometime in 1.0.1.x.

**Comment by faithfulzeal** [comment]
Any news on this?

**Comment by ThinkInvis** [comment]
I've learned today that the fix for this issue is present in the beta branch of RoR2, which is going through QA and may be released sometime soon.

**Comment by ThinkInvis** [comment]
Fixed as of Risk of Rain 2 v1.0.1.1.
