### ISSUE TITLE
H3AD-5T v2 doesn't work at all with mod installed

### ISSUE THREAD

**Issue by JeanetJules** [ThinkInvis/RoR2-ClassicItems#48]
I can't say much more, I've tried with and without Headhompers in my inventory.

**Comment by ThinkInvis** [comment]
This is intended behavior. H3AD-5T v2 should only increase jump height and prevent fall damage, unless you've changed the Global > HSV2NoStomp config option to False. This was due to the overlap in functionality with Headstompers and Photon Jetpack.

However, due to the recent change to H3AD-5T v2 which made its controls less intrusive -- and its attack much more powerful than Headstompers' -- I'll be removing this as a default-enabled option (75bf0a2ca8e43a64e881d84ceb8a4331225d1dc2). As you've installed the mod already, you'll have to change the config yourself.

**Comment by JeanetJules** [comment]
Thanks for the reply !  UwU will do. Amazing mod btw.
