### ISSUE TITLE
standalone version for just a couple of items?

### ISSUE THREAD

**Issue by TheHolyDerp** [ThinkInvis/RoR2-ClassicItems#56]
hey there, I want to use this mod's red items (except for jetpack) and only them, is there a way I can do this? disabling in config isn't an option as that disables base items as well.

**Comment by ThinkInvis** [comment]
https://github.com/ThinkInvis/RoR2-ClassicItems/issues/42 is likely to be fixed by the RoR2 devs soon (already done in beta branch). Disabling items through config is the intended way to limit usage, and the only one I'll support -- splitting off partial copies of mods to work around temporary issues is a good way to clutter Thunderstore, and to make it harder to develop the mod.
