### ISSUE TITLE
The mod stopped working after the anniversary update.

### ISSUE THREAD

**Issue by SpaceKittin** [ThinkInvis/RoR2-ClassicItems#77]
It stopped working and idk why.

**Comment by cheeeeeeeeeen** [comment]
This is a known issue. Standby for an R2API update.

**Comment by VaelophisNyx** [comment]
R2API is now updated. Assuming it's being worked on, is there any ETA on an update?

**Comment by ThinkInvis** [comment]
I've been on hiatus, and planned on coming back for the anniversary update. It may take a while (at least a few days) to update TILER2 and then this, as I'm working on relearning everything -- and a lot seems to have changed/otherwise broken. I may or may not also need to wait for further R2API updates to avoid making major structural changes to TILER2.

**Comment by ThinkInvis** [comment]
Fixed in public release 5.0.0.
