### ISSUE TITLE
Void No Longer Gives Items After Completion

### ISSUE THREAD

**Issue by TheDankestJew** [ThinkInvis/RoR2-ClassicItems#82]
### Void Cell Completion No Longer Gives Items
When you complete a void cell you will not get any items in return

### To Reproduce
1. Go to the void
2. Complete void cell
3. No items after completion

**Comment by DragonTrainerBen** [comment]
Issue appears to likely be this mods dependency, TILER2 rather than ClassicItems. 
Issue occurs while TILER2 is enabled, regardless of whether ClassicItems is enabled, disabled, or uninstalled.

Link to the issue posting on TILER2:
https://github.com/ThinkInvis/RoR2-TILER2/issues/17

Log with core mods and TILER2, full void field. 
[LogOutput.txt](https://github.com/ThinkInvis/RoR2-ClassicItems/files/6269318/LogOutput.txt)

**Comment by ThinkInvis** [comment]
It's an issue with R2API: https://github.com/ThinkInvis/RoR2-ClassicItems/issues/80#issuecomment-814224521

**Comment by ThinkInvis** [comment]
Appears to have been fixed by R2API 3.0.11.
