### ISSUE TITLE
It won't properly uninstall. 

### ISSUE THREAD

**Issue by Zavern** [ThinkInvis/RoR2-ClassicItems#85]
### To Reproduce
1. Install Mod
2. Uninstall Mod

### Expected Behavior
All files are removed from the computer without issue.

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-ClassicItems/files/6291229/LogOutput.log)

### Additional Context
Add any other context about the problem here (screenshots, etc.).

**Comment by ThinkInvis** [comment]
I can't address a bug without a description of what the bug is. Also, ClassicItems doesn't appear at all in that console log. It isn't structured any differently than most mods; if files are lingering unexpectedly (best guess based on 'expected behavior' section), it's either a mod manager bug or user error.
